// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	tutorialSidebar: [
		'Introduction',
		{
			type: 'category',
			label: '🚀 Getting started',
			link: {
				type: 'generated-index',
				description: 'And to start, take a moment to familiarize yourself with the module...',
			},
			items: [
				'Getting-started/Installation',
				{
					type: 'category',
					label: '🤖 Creating Your Bot',
					collapsed: false,
					link: {
						type: 'generated-index',
						description: 'Here are examples that you can implement in your discord application at the start',
					},
					items: [
						'Getting-started/Examples/configuration',
						'Getting-started/Examples/main-file',
						'Getting-started/Examples/creating-commands',
						'Getting-started/Examples/command-handling',
						'Getting-started/Examples/event-handling',
						'Getting-started/Examples/deployment-script',
					],
				},
			],
		},
		{
			type: 'category',
			label: '🧩 Classes',
			collapsed: false,
			link: {
				type: 'generated-index',
				description: 'Classes are the most important part of the module, so take a look at them...',
			},
			items: [
				{
					type: 'autogenerated',
					dirName: 'Classes',
				},
			],
		},
		{
			type: 'category',
			label: '🧮 Enums',
			link: {
				type: 'generated-index',
				description: 'Important enumerations...',
			},
			items: [
				{
					type: 'autogenerated',
					dirName: 'Enums',
				},
			],
		},
		{
			type: 'category',
			label: '🧾 Typedefs',
			link: {
				type: 'generated-index',
				description: 'Typedefs is the second most important part of the module, so take a look at them...',
			},
			items: [
				{
					type: 'autogenerated',
					dirName: 'Typedefs',
				},
			],
		},
	],
};

export default sidebars;
