// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'introduction',
    {
      type: 'category',
      label: '🚀 Getting started',
      link: {
        type: "generated-index",
        description: "5 minutes to learn the most important Docusaurus concepts."
      },
      items: [
        {
          type: 'doc',
            id: 'Getting-started/test',
        },
          {
            type: 'category',
            label: '👀 Basics',
            link: {
              type: "generated-index",
              description: "5 minutes to learn the most important Docusaurus concepts."
            },
            items: [
              'Getting-started/Basics/index-js',
              'Getting-started/Basics/play-command',
              'Getting-started/Basics/events'
            ],
          }
      ],
    },
    {
      type: 'category',
      label: '🏛️ Classes',
      link: {
        type: "generated-index",
        description: "5 minutes to learn the most important Docusaurus concepts."
      },
      items: [
        {
          type: "autogenerated",
          dirName: "Classes"
        }
      ],
    },
    {
      type: 'category',
      label: '🎈 Typedefs',
      link: {
        type: "generated-index",
        description: "5 minutes to learn the most important Docusaurus concepts."
      },
      items: [
        {
          type: "autogenerated",
          dirName: "Typedefs"
        }
      ],
    }
  ],

  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   {
  //     type: 'category',
  //     label: '✨ Introduction',
  //     items: ['getting-started'],
  //   },
  // ],
};

export default sidebars;
